"""add insurance_number to patient

Revision ID: 6ccd3fcd1b21
Revises: merged_20251218
Create Date: 2025-12-18 15:52:54.593032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccd3fcd1b21'
down_revision = 'merged_20251218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('insurance_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'insurance_number')
    # ### end Alembic commands ###
